PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX mbr: <http://mosaicbookstore.com/mbr/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

PREFIX owl: <http://www.w3.org/2002/07/owl#>

CONSTRUCT {
    ?authorCsv owl:sameAs ?dbpAuthor .
}
FROM <schema.ttl>
WHERE {
  ?authorCsv rdf:type mbr:Author ;
             mbr:fullName ?fullName .
  SERVICE <http://dbpedia.org/sparql> {
    ?dbpAuthor rdf:type dbo:Writer ;
               foaf:name ?dbpName .
  }
  FILTER(LCASE(str(?fullName)) = LCASE(str(?dbpName)))
}