PREFIX football: <http://example.org/football/>

SELECT ?match (COUNT(?goal) AS ?nbGoals)
WHERE {
  GRAPH <http://ex/goal> {
    ?goal a football:Goal ;
          football:scoredIn ?match .
  }
  GRAPH <http://ex/match> {
    ?match ?p ?o .
  }
}
GROUP BY ?match
ORDER BY (?nbGoals)
LIMIT 10
