PREFIX ex: <http://example.org/ />

SELECT DISTINCT ?match ?p1 ?p2
WHERE {
  GRAPH <http://ex/goal> {
    ?p1 ( ^ex:scoredBy / ex:scoredIn ) ?match .
    ?p2 ( ^ex:scoredBy / ex:scoredIn ) ?match .
  }

  FILTER(?p1 != ?p2)
  FILTER(STR(?p1) < STR(?p2))
}
LIMIT 10
