PREFIX football: <http://example.org/football/>

SELECT ?player (COUNT(?goal) AS ?nb)
WHERE {
  GRAPH <http://example.org/g/goals> {
    ?goal a football:Goal ;
          football:scoredBy ?player .
  }
}
GROUP BY ?player
ORDER BY DESC(?nb)
LIMIT 10
